Flask/BetterUnderstandingofFlaskfromzero/application/flask_blog/models/entries.py
# データベースモジュールのインポート
from flask_blog import db
# 日付を扱うモジュールをインポート
from datetime import datetime

class Entry(db.Model):
    # テーブルの名前
    __tablename__ = 'entries'
    # 主キー
    id = db.Column(db.Integer, primary_key=True)
    # ユニークキー
    title = db.Column(db.String(50), unique=True)
    text = db.Column(db.Text)
    created_at = db.Column(db.DateTime)

    # コンストラクタ
    def __init__(self, title=None, text=None):
        self.title = title
        self.text = text
        self.created_at = datetime.utcnow() # UTC時間

    # コンソールの出力形式
    def __repr__(self):
        return '<Entry id:{} title:{} text:{}>'.format(self.id, self.title, self.text)

Flask/BetterUnderstandingofFlaskfromzero/application/flask_blog/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object('flask_blog.config')

db = SQLAlchemy(app)

from flask_blog.views.entries import entry

app.register_blueprint(entry, url_prefix='/users')

from flask_blog.views import view, entries

Flask/BetterUnderstandingofFlaskfromzero/application/flask_blog/views/entries.py
from flask import request, redirect, url_for, render_template, flash, session
from flask_blog import app
from flask_blog import db
from flask_blog.models.entries import Entry
from flask_blog.views.view import login_required
from flask import Blueprint

# Blueprintを使ってentryを分離する
entry = Blueprint('entry', __name__)

# http://127.0.0.1:5000/にリクエストが有ったときにshow_entriesメソッドを呼び出す
@entry.route('/')
@login_required
def show_entries():
    # 文字列を返し，ブラウザに表示する
    # return "Hello World!"
    # templatesフォルダ以下にあるentries/index.htmlを返してレンダリングする
    # ログインしたというセッション情報がなければログイン画面へ遷移する
    # if not session.get('logged_in'):
    #     return redirect(url_for('login'))
    # 全データをDBから取得する
    entries = Entry.query.order_by(Entry.id.desc()).all()
    return render_template('entries/index.html', entries=entries)

# ブログを投稿するメソッド
@entry.route('/entries/new', methods=['GET'])
@login_required
def new_entry():
    # if not session.get('logged_in'):
    #     return redirect(url_for('login'))
    return render_template('entries/new.html')

@entry.route('/entries', methods=['POST'])
@login_required
def add_entry():
    # if not session.get('logged_in'):
    #     return redirect(url_for('login'))
    entry = Entry(
        title = request.form['title'],
        text = request.form['text']
    )
    db.session.add(entry)
    db.session.commit()
    flash('新しく記事が作成されました')
    return redirect(url_for('entry.show_entries'))

# url_forで渡されるIDをint型に指定
@entry.route('/entries/<int:id>', methods=['GET'])
@login_required
def show_entry(id):
    # if not session.get('logged_in'):
    #     return render_template(url_for('login'))
    entry = Entry.query.get(id)
    return render_template('entries/show.html', entry=entry)

@entry.route('/entries/<int:id>/edit', methods=['GET'])
@login_required
def edit_entry(id):
    # if not session.get('logged_in'):
    #     return redirect(url_for('login'))
    entry = Entry.query.get(id)
    return render_template('entries/edit.html', entry=entry)

# 更新処理
@entry.route('/entries/<int:id>/update', methods=['POST'])
@login_required
def update_entry(id):
    # if not session.get('logged_in'):
    #     return redirect(url_for('login'))
    entry = Entry.query.get(id)
    entry.title = request.form['title']
    entry.text = request.form['text']
    db.session.merge(entry)
    db.session.commit()
    flash('記事が更新されました')
    return redirect(url_for('entry.show_entries'))

# 削除処理
@entry.route('/entries/<int:id>/delete', methods=['POST'])
@login_required
def delete_entry(id):
    # if not session.get('logged_in'):
    #     return redirect(url_for('login'))
    entry = Entry.query.get(id)
    db.session.delete(entry)
    db.session.commit()
    flash('投稿が削除されました')
    return redirect(url_for('entry.show_entries'))

Flask/BetterUnderstandingofFlaskfromzero/application/flask_blog/views/view.py
from flask import request, redirect, url_for, render_template, flash, session
from flask_blog import app
from functools import wraps

def login_required(view):
    @wraps(view)
    def inner(*args, **kwargs):
        if not session.get('logged_in'):
            return redirect(url_for('login'))
        return view(*args, **kwargs)
    return inner

# loginリンクをクリックするときはGETメソッドが
# ログインフォームのデータ送信にはPOSTメソッドが使われる
@app.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    # POSTならば
    if request.method == 'POST':
        if request.form['username'] != app.config['USERNAME']:
            flash('ユーザ名が異なります')
        elif request.form['password'] != app.config['PASSWORD']:
            flash('パスワードが異なります')
        else: # ログイン成功ならば
            # セッションにログインしたという情報を格納
            session['logged_in'] = True
            flash('ログインしました')
            return redirect(url_for('entry.show_entries'))
    return render_template('login.html')

@app.route('/logout')
def logout():
    # セッションからログインしたという情報を破棄
    session.pop('logged_in', None)
    flash('ログアウトしました')
    return redirect(url_for('login'))

@app.errorhandler(404)
def non_existant_route(error):
    return redirect(url_for('login'))

Flask/BetterUnderstandingofFlaskfromzero/application/flask_blog/templates/entries/edit.html
{% extends "layout.html" %}
{% block body %}
  <form class=add-entry action="{{ url_for('entry.update_entry', id=entry.id) }}" method=post>
    <div class="form-group">
      <label for="InputTitle">タイトル</label>
      <input type="text" name=title value={{ entry.title }} id="InputTitle" class="form-control">
    </div>
    <div class="form-group">
      <label for="InputText">本文</label>
      <textarea name=text rows="3" id="InputText" class="form-control">{{ entry.text | safe }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">更新</button>
  </form>
{% endblock %}

Flask/BetterUnderstandingofFlaskfromzero/application/flask_blog/templates/entries/index.html
{% extends "layout.html" %}
{% block body %}
  <ul class="list-group list-group-flush">
    {% for entry in entries %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ entry.title }}</h5>
        <a href="{{ url_for('entry.show_entry', id=entry.id) }}" class="card-link">続きを読む</a>
      </div>
    </div>
    {% else %}
    投稿がありません
    {% endfor %}
  </ul>
{% endblock %}

Flask/BetterUnderstandingofFlaskfromzero/application/flask_blog/templates/entries/new.html
{% extends "layout.html" %}
{% block body %}
<form class=add-entry action="{{ url_for('entry.add_entry') }}" method=post>
  <div class="form-group">
    <label for="InputTitle">タイトル</label>
    <input type="text" name=title class="form-control" id="InputTitle">
  </div>

  <div class="form-group">
    <label for="InputText">本文</label>
    <textarea name=text rows="3" class="form-control" id="InputText"></textarea>
  </div>
  <button type="submit" class="btn btn-primary">作成</button>
</form>
{% endblock %}

Flask/BetterUnderstandingofFlaskfromzero/application/flask_blog/templates/entries/show.html
{% extends 'layout.html' %}
{% block body %}
  <h2>{{ entry.title }}</h2>
  <br>
  {{ entry.text | safe }}

  <br><br>
  投稿日時: {{ entry.created_at }}
  <br><br>
  <div class="btn-group">
    <form action="{{ url_for('entry.edit_entry', id=entry.id) }}" method="get">
      <button type="submit" class="btn btn-secondary">編集</button>
    </form>
    <form action="{{ url_for('entry.delete_entry', id=entry.id) }}" method="post">
      <button type="submit" class="btn btn-danger" style="margin-left:5px">削除</button>
    </form>
  </div>
{% endblock %}

Flask/BetterUnderstandingofFlaskfromzero/application/flask_blog/templates/layout.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>Flask Blog</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <!-- フォントCSS -->
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p&amp;subset=japanese" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a href="{{ url_for('entry.show_entries') }}" class="navbar-brand">Flask Blog</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav", aria-expanded="false", aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="nav navbar-nav navbar-right">
            <!-- ログインしてなかったら -->
            {% if not session.logged_in %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('login') }}">ログイン</a>
            </li>
            <!-- ログインしていたら -->
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('entry.new_entry') }}">新規投稿</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('logout') }}">ログアウト</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>

      {% for message in get_flashed_messages() %}
      <div class="alert alert-info" role="alert">
        {{ message }}
      </div>
      {% endfor %}

      <div class="blog-body">
        {% block body %}{% endblock %}
      </div>
    </div>
  </body>
</html>

Flask/BetterUnderstandingofFlaskfromzero/application/flask_blog/templates/login.html
{% extends "layout.html" %}
{% block body %}
  <form action="{{ url_for('login') }}" method="post">
    <div class="form-group">
      <label for="InputTitle">ユーザ名</label>
      <input type="text" name=username class="form-control" id="InputTitle">
    </div>
    <div class="form-group">
      <label for="InputPassword">パスワード</label>
      <input type="password" name=password class="form-control" id="InputPassword">
    </div>
    <button type="submit" class="btn btn-primary">ログイン</button>
  </form>
{% endblock %}